LEARN_MORE_TEXT = "Learn more"
IANA_HEADING = "Example Domains"
HOMEPAGE_HEADING = "Example Domain"
IANA_URL = "https://www.iana.org/help/example-domains"
LEARN_MORE_HREF = "https://iana.org/domains/example"